apiVersion: "v1"
kind: "Service"
metadata:
  name: "motomura-io"
  namespace: "motomura"
  labels:
    app: "motomura-io"
spec:
  type: ClusterIP
  selector:
    app: "motomura-io"
  ports:
    - name: http
      port: 80
      targetPort: 80