apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: motomura
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis

  template:
    metadata:
      labels:
        app: redis

    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          resizePolicy:
            - resourceName: cpu
              restartPolicy: NotRequired
            - resourceName: memory
              restartPolicy: NotRequired
          ports:
            - containerPort: 6379

          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: REDIS_PASSWORD

          volumeMounts:
            - name: redis-storage
              mountPath: /data

          command:
            - redis-server

          args:
            - "--requirepass"
            - "$(REDIS_PASSWORD)"
            - "--appendonly"
            - "yes"
            - "--maxmemory"
            - "2gb" 
            - "--maxmemory-policy"
            - "allkeys-lru"

          resources:
            requests:
              cpu: 350m
              memory: 512Mi

            limits:
              cpu: 1000m
              memory: 4Gi

      volumes:
        - name: redis-storage
          persistentVolumeClaim:
            claimName: redis-pvc